### ISSUE TITLE
Include locust.conf file

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn-sandbox/locust-service#11]
Locust also provides config files for running the tests.
https://docs.locust.io/en/stable/configuration.html#configuration-file 

The Keptn integration should support the use of config files.

**Comment by jetzlstorfer** [comment]
A first draft for a mapping file `locust.conf.yaml` similar to the one for the jmeter-service (take a look at the [readme here](https://github.com/keptn/keptn/tree/master/jmeter-service#custom-workloads))

```
---
spec_version: '0.1.0'
workloads:
  - teststrategy: performance_heavy
    script: ./performance.py
    conf: ./performance.conf
  - teststrategy: performance_light
    script: ./performance.py
    conf: ./performance_light.conf
  - teststrategy: functional
    script: ./func.py

```

**Comment by jetzlstorfer** [comment]
As discussed with Lars from the Locust community, the integration should work like this:

- If no config file `locust.conf.yaml` is given, the integration should look for a default file to look for should be `locustfile.py` as this is the standard in Locust.
- If a config file `locust.conf.yaml` is given, the integration should use this.

The contents of `locust.conf.yaml` should be used as described in the following:
- If a "script" is given, it has to be used in the execution of the locust test.
- If "script" is not given, we can assume that the script is part of the "config" file that is referenced.
- If a "conf" is given, it should be used in the execution of the locust test.
- If "conf" is not given, we need to check if  "script" is given.
- If both are missing, the integration should skip the tests and indicate this in the result that is sent back to Keptn 

```
---
spec_version: '0.1.0'
workloads:
  - teststrategy: performance_heavy
    script: ./performance.py      # performance.py is used regardless what is specified in performance.conf
    conf: ./performance.conf 
  - teststrategy: performance_light
    conf: ./performance_light.conf     # a *.py has to be defined in the performance_light.conf file
  - teststrategy: functional
    script: ./func.py                   # no configuration is used
```
